name: deploy-cd
on:
  push:
    branches:
      - master
env:
  VERSION_FILE: ./package.json
  VERSION_EXTRACT_PATTERN: '"version": "([^"]+)",'
jobs:
  deploy:
    name: deploy
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install
      - run: yarn build
      - name: Version
        uses: HardNorth/github-version-generate@v1.0.2
        with:
          version-source: file
          version-file: ${{ env.VERSION_FILE }}
          version-file-extraction-pattern: ${{ env.VERSION_EXTRACT_PATTERN }}
      - name: Move to directory
        run: |
          git fetch origin
          mv package.json build/
          git checkout gh-pages
          rm .eslintcache *.html *.ico *.json *.png *.txt
          rm -rf static/
          mv build/* ./
      - name: Add & Commit
        run: |
          git add -- . ':!build' ':!node_modules' ':!package.json'
          git commit -m "Release: v${{ env.RELEASE_VERSION }}"
          git push origin gh-pages

